//CHATBOT
export const SEND_MESSAGE_SAGA = 'SEND_MESSAGE_SAGA';
export const SEND_IMG_MESSAGE_SAGA = 'SEND_IMG_MESSAGE_SAGA';

//VIDEO
export const GET_VIDEO_SAGA = 'GET_VIDEO_SAGA';

//NEWS
export const GET_NEWS_SAGA = 'GET_NEWS_SAGA';

//PRODUCTS
export const GET_JOBS_SAGA = 'GET_JOBS_SAGA';

//SHOP
export const GET_LOCALSTORES_SAGA = 'GET_LOCALSTORES_SAGA';
